using System.Collections.Generic;

namespace WordScrambler
{
    public class WordBuilder
    {
        public static List<string> GetWords()
        {
            return new List<string> {
                "agility",
                "beauty",
                "decency",
                "decorum",
                "dexterity",
                "ease",
                "elegance",
                "finesse",
                "poise",
                "refinement",
                "style",
                "address",
                "adroitness",
                "allure",
                "attractiveness",
                "balance",
                "breeding",
                "comeliness",
                "consideration",
                "cultivation",
                "etiquette",
                "finish",
                "form",
                "gracefulness",
                "lissomeness",
                "manners",
                "nimbleness",
                "pleasantness",
                "pliancy",
                "polish",
                "propriety",
                "shapeliness",
                "smoothness",
                "suppleness",
                "symmetry",
                "tact",
                "tastefulness",
                "lithesomeness",
                "mannerliness",
                "bad manners",
                "clumsiness",
                "crudeness",
                "indecency",
                "rudeness",
                "ugliness",
                "disproportion",
                "ignorance",
                "imbalance",
                "neglect",
                "thoughtlessness",
                "ineptness",
                "mercilessness",
                "tactlessness",
                "unforgiveness",

                "central",
                "familiar",
                "family",
                "household",
                "local",
                "national",
                "native",
                "at ease",
                "at rest",
                "down home",
                "homely",
                "homey",
                "in one's element",
                "in the bosom",
                "inland",
                "internal",
                "foreign",
                "outside",
                "business",
                "commercial",

                "affection",
                "appreciation",
                "devotion",
                "emotion",
                "fondness",
                "friendship",
                "infatuation",
                "passion",
                "respect",
                "taste",
                "tenderness",
                "yearning",
                "adulation",
                "allegiance",
                "amity",
                "amorousness",
                "amour",
                "ardor",
                "attachment",
                "case",
                "cherishing",
                "crush",
                "delight",
                "devotedness",
                "enchantment",
                "enjoyment",
                "fervor",
                "fidelity",
                "flame",
                "hankering",
                "idolatry",
                "inclination",
                "involvement",
                "like",
                "partiality",
                "piety",
                "rapture",
                "regard",
                "relish",
                "sentiment",
                "weakness",
                "worship",
                "zeal",
                "ardency",
                "mad for",
                "soft spot",
                "animosity",
                "dislike",
                "enmity",
                "hate",
                "hatred",
                "ill will",
                "indifference",
                "neglect",
                "apathy",
                "coolness",
                "disloyalty",
                "misery",
                "sorrow",
                "treachery",
                "unhappiness",

                "amusement",
                "bliss",
                "charm",
                "cheer",
                "comfort",
                "delight",
                "elation",
                "glee",
                "humor",
                "pride",
                "satisfaction",
                "wonder",
                "alleviation",
                "animation",
                "delectation",
                "diversion",
                "ecstasy",
                "exultation",
                "exulting",
                "felicity",
                "festivity",
                "frolic",
                "fruition",
                "gaiety",
                "gem",
                "gladness",
                "gratification",
                "hilarity",
                "indulgence",
                "jewel",
                "jubilance",
                "liveliness",
                "luxury",
                "merriment",
                "mirth",
                "prize",
                "rapture",
                "ravishment",
                "refreshment",
                "rejoicing",
                "revelry",
                "solace",
                "sport",
                "transport",
                "treasure",
                "treat",
                "good humor",
                "pride and joy",
                "regalement",
                "depression",
                "melancholy",
                "misery",
                "sadness",
                "seriousness",
                "sorrow",
                "unhappiness",
                "discouragement",
                "dislike",
                "mourning",
                "vocation",
                "work",
                "woe",

                "ask",
                "beseech",
                "recite",
                "urge",
                "adjure",
                "appeal",
                "brace",
                "crave",
                "entreat",
                "implore",
                "importune",
                "invoke",
                "petition",
                "request",
                "say",
                "solicit",
                "sue",
                "supplicate",
                "commune with",
                "cry for",
                "invocate",
                "answer",
                "refuse",

                "trek",
                "trip",
                "backpack",
                "constitutional",
                "excursion",
                "exploration",
                "march",
                "ramble",
                "tour",
                "traipse",
                "tramp",
                "walk",
                "walkabout",

                "pedal",
                "cycle",

                "alive",
                "animate",
                "breathing",
                "living",
                "aware",
                "conscious",
                "vital",
                "dead",
                "apathetic",
                "dispirited",
                "inactive",
                "lethargic",
                "non-existent",

                "offspring",
                "whelp",

                "blossom",
                "flower",
                "blossoming",
                "bud",
                "efflorescence",
                "floret",
                "flourishing",
                "floweret",
                "opening",

                "beam",
                "grin",
                "laugh",
                "smirk",
                "simper",
                "be gracious",
                "express friendliness",
                "express tenderness",
                "look amused",
                "look delighted",
                "look happy",
                "look pleased",
                "frown",
                "glower",

                "vacation",
                "break",
                "breather",
                "calm",
                "calmness",
                "cessation",
                "comfort",
                "composure",
                "cutoff",
                "downtime",
                "doze",
                "dreaminess",
                "ease",
                "halt",
                "holiday",
                "hush",
                "idleness",
                "interlude",
                "intermission",
                "interval",
                "leisure",
                "letup",
                "lull",
                "motionlessness",
                "nap",
                "pause",
                "peace",
                "quiescence",
                "quiet",
                "quietude",
                "recess",
                "recreation",
                "refreshment",
                "relaxation",
                "relief",
                "repose",
                "respite",
                "siesta",
                "silence",
                "sleep",
                "slumber",
                "somnolence",
                "standstill",
                "stay",
                "stillness",
                "stop",
                "tranquillity",
                "breathing space",
                "coffee break",
                "forty winks",
                "time off",
                "advance",
                "agitation",
                "awakening",
                "beginning",
                "busyness",
                "clamor",
                "consciousness",
                "continuation",
                "distress",
                "disturbance",
                "employment",
                "go",
                "hurt",
                "injury",
                "labor",
                "noise",
                "start",
                "upset",
                "wakefulness",
                "work",
                "worry",
                "action",
                "activity",
                "base",
                "core",
                "energy",
                "achievement",
                "ambition",
                "anticipation",
                "aspiration",
                "belief",
                "concern",
                "confidence",
                "desire",
                "expectation",
                "faith",
                "goal",
                "optimism",
                "promise",
                "prospect",
                "wish",
                "assumption",
                "buoyancy",
                "daydream",
                "dependence",
                "endurance",
                "expectancy",
                "fancy",
                "fortune",
                "gain",
                "hopefulness",
                "reliance",
                "reverie",
                "reward",
                "rosiness",
                "sanguineness",
                "security",
                "stock",
                "utopia",
                "Promised Land",
                "bright side",
                "castles in air",
                "fool's paradise",
                "greedy glutton",
                "light at end of tunnel",
                "pipe dream",
                "thing with feathers",
                "disbelief",
                "dislike",
                "distrust",
                "doubt",
                "fear",
                "hate",
                "hatred",
                "hopelessness",
                "fact",
                "reality",
                "truth",
                "despair",
                "discouragement",
                "pessimism",
                "delusion",
                "fantasy",
                "idea",
                "image",
                "imagination",
                "nightmare",
                "thought",
                "bubble",
                "chimera",
                "daydream",
                "fancy",
                "hallucination",
                "impression",
                "incubus",
                "rainbow",
                "reverie",
                "specter",
                "speculation",
                "trance",
                "vagary",
                "wraith",
                "castle in the air",
                "head trip",
                "mental picture",
                "pie in the sky",
                "pipe dream",
                "concrete",
                "entity",
                "reality",
                "truth",
                "fact",
                "actuality",
                "certainty",
                "existence",
                "substance",
                "accord",
                "friendship",
                "love",
                "reconciliation",
                "truce",
                "unity",
                "amity",
                "armistice",
                "cessation",
                "conciliation",
                "concord",
                "neutrality",
                "order",
                "pacification",
                "pacifism",
                "treaty",
                "unanimity",
                "union",
                "disagreement",
                "hate",
                "hatred",
                "discord",
                "agitation",
                "disharmony",
                "distress",
                "fighting",
                "frustration",
                "upset",
                "war",
                "worry",
                "chuckle",
                "giggle",
                "grin",
                "howl",
                "roar",
                "scream",
                "shriek",
                "snicker",
                "snort",
                "whoop",
                "burst",
                "cachinnate",
                "chortle",
                "convulsed",
                "crow",
                "fracture",
                "guffaw",
                "titter",
                "break up",
                "crack up",
                "die laughing",
                "roll in the aisles",
                "split one's sides",
                "with sound be in stitches",
                "cry",
                "accord",
                "allow",
                "award",
                "commit",
                "deliver",
                "donate",
                "grant",
                "hand out",
                "hand over",
                "permit",
                "present",
                "provide",
                "sell",
                "turn over",
                "administer",
                "bequeath",
                "bestow",
                "cede",
                "confer",
                "consign",
                "convey",
                "deed",
                "dispense",
                "endow",
                "entrust",
                "furnish",
                "gift",
                "lease",
                "relinquish",
                "remit",
                "subsidize",
                "tip",
                "transmit",
                "vouchsafe",
                "will",
                "ante up",
                "come across",
                "dish out",
                "dispose of",
                "dole out",
                "fork over",
                "hand down",
                "heap upon",
                "lavish upon",
                "lay upon",
                "let have",
                "make over",
                "parcel out",
                "part with",
                "pass down",
                "pass out",
                "pony up",
                "shell out",
                "throw in",
                "deny",
                "disallow",
                "disapprove",
                "hold",
                "keep",
                "receive",
                "refuse",
                "reject",
                "retain",
                "take",
                "withhold",
                "conceal",
                "hide",
                "neglect",
                "fight",
                "hold up",
                "refrain",
                "withstand",
                "gather",
                "interpret",
                "know",
                "learn",
                "refer to",
                "scan",
                "see",
                "study",
                "translate",
                "view",
                "apprehend",
                "comprehend",
                "construe",
                "decipher",
                "discover",
                "glance",
                "perceive",
                "peruse",
                "skim",
                "unravel",
                "bury oneself in",
                "dip into",
                "flip through",
                "go over",
                "go through",
                "leaf through",
                "make out",
                "pore over",
                "scratch the surface",
                "forget",
                "ignore",
                "misinterpret",
                "misunderstand",
                "neglect",
                "overlook",
                "lose",
                "miss",
                "write",
                "anoint",
                "baptize",
                "consecrate",
                "ordain",
                "thank",
                "absolve",
                "beatify",
                "canonize",
                "commend",
                "confirm",
                "cross",
                "dedicate",
                "enshrine",
                "eulogize",
                "exalt",
                "extol",
                "glorify",
                "hallow",
                "honor",
                "laud",
                "magnify",
                "offer",
                "praise",
                "sacrifice",
                "sign",
                "sprinkle",
                "give thanks to",
                "invoke benefits",
                "invoke happiness",
                "make holy",
                "offer benediction",
                "panegyrize",
                "pray for",
                "pronounce holy",
                "blame",
                "castigate",
                "censure",
                "condemn",
                "criticize",
                "debase",
                "denounce",
                "deny",
                "desecrate",
                "disrespect",
                "hold",
                "humiliate",
                "refuse",
                "reproach",
                "shame",
                "take",
                "curse",
                "damn",
                "disallow",
                "disapprove",
                "veto",
                "attention",
                "celebration",
                "confidence",
                "credit",
                "dignity",
                "distinction",
                "esteem",
                "faith",
                "fame",
                "glory",
                "praise",
                "prestige",
                "recognition",
                "reputation",
                "tribute",
                "trust",
                "account",
                "adoration",
                "adulation",
                "aggrandizement",
                "apotheosis",
                "approbation",
                "canonization",
                "consideration",
                "deference",
                "deification",
                "elevation",
                "exaltation",
                "fealty",
                "glorification",
                "greatness",
                "homage",
                "laud",
                "laurel",
                "notice",
                "obeisance",
                "popularity",
                "rank",
                "renown",
                "repute",
                "reverence",
                "veneration",
                "worship",
                "wreath",
                "high standing",
                "immortalization",
                "lionization",
                "blame",
                "criticism",
                "disbelief",
                "disclaimer",
                "dishonor",
                "disregard",
                "distrust",
                "doubt",
                "ignorance",
                "ill repute",
                "lowliness",
                "unimportance",
                "depression",
                "disdain",
                "disobedience",
                "disrespect",
                "heedlessness",
                "neglect",
                "scorn",
                "blemish",
                "censure",
                "condemnation",
                "debasement",
                "degradation",
                "denunciation",
                "derision",
                "disgrace",
                "humiliation",
                "reproach",
                "stigma",
                "blizzard",
                "snowfall",
                "snow flurry",
                "America",
                "Columbia",
                "Land of Liberty",
                "New World",
                "U.S.",
                "U.S.A.",
                "US",
                "US of A",
                "USA",
                "land of opportunity",
                "the States",
                "acceptance",
                "belief",
                "confidence",
                "conviction",
                "hope",
                "loyalty",
                "truth",
                "allegiance",
                "assent",
                "assurance",
                "certainty",
                "certitude",
                "constancy",
                "credence",
                "credit",
                "credulity",
                "dependence",
                "faithfulness",
                "fealty",
                "fidelity",
                "reliance",
                "stock",
                "store",
                "sureness",
                "surety",
                "troth",
                "truthfulness",
                "disbelief",
                "disloyalty",
                "dishonesty",
                "distrust",
                "doubt",
                "faithlessness",
                "inconstancy",
                "lying",
                "treachery",
                "uncertainty",
                "unsteadiness",
                "agnosticism",
                "denial",
                "misgiving",
                "rejection",
                "skepticism",
                "suspicion",
                "unbelief"
            };
        }
    }
}